apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocdapp
  namespace: default
  labels:
    app: argocdapp
spec:
  replicas: 2  # Number of pod replicas
  selector:
    matchLabels:
      app: argocdapp
  template:
    metadata:
      labels:
        app: argocdapp
    spec:
      containers:
        - name: argocdapp
          image: ogunmolu/argocd  # Container image
          imagePullPolicy: Always
          ports:
            - containerPort: 3000  # Exposing port