apiVersion: v1
kind: Service
metadata:
  name: argocdapp 
  namespace: default  
  labels:
    app: argocdapp    
spec:
  selector:
    app: argocdapp   
  ports:
    - protocol: TCP    
      port: 3000        
      targetPort: 3000 
  type: LoadBalancer      
  